version: '3'

services:
  webapp:
    image: auctionservice
    ports:
      - "7001:8080"
    volumes:
      - ./appsettings.json:/app/appsettings.json
    build:
      context: .
      dockerfile: Dockerfile
